name: keep-alive

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull-docker-image
        run: |
          docker pull freethenation/kube-debug-container:latest
